const config = {
  name: 'one-figma-shortcut-a-day',
  macShortcuts: [
    {
      label:
        'Show/Hide UI\nPress it now to quickly hide the panes and focus on your work',
      keys: '⌘\n\\',
    },
    {
      label: 'Pick Color\nGrab a color from elsewhere without losing your flow',
      keys: '⌃\nC',
    },
    { label: 'Search…\nSearch through all of Figma’s commands', keys: '⌘\n/' },
    { label: 'Show Assets', keys: '⌥\n2' },
    { label: 'Team Library', keys: '⌥\n⌘\nO' },
    { label: 'Create Component', keys: '⌥\n⌘\nK' },
    { label: 'Detach Instance', keys: '⌥\n⌘\nB' },
    { label: 'Swap Component Instance', keys: '⌥' },
    { label: 'Bring Forward', keys: '⌘\n]' },
    { label: 'Send Backward', keys: '⌘\n[' },
    { label: 'Bring to Front', keys: '⌥\n⌘\n]' },
    { label: 'Send to Back', keys: '⌥\n⌘\n[' },
    { label: 'Align Left/Right', keys: '⌥\nA\nand\nD' },
    { label: 'Align Top/Bottom', keys: '⌥\nW\nand\nS' },
    { label: 'Align Centers', keys: '⌥\nH\nand\nV' },
    { label: 'Distribute Spacing', keys: '⌃\n⌥\nH\nand\nV' },
    { label: 'Tidy Up', keys: '⌃\n⌥\nT' },
    { label: 'Add Auto Layout', keys: '⇧\nA' },
    { label: 'Remove Auto Layout', keys: '⌥\n⇧\nA' },
    { label: 'Flip Horizontal', keys: '⇧\nH' },
    { label: 'Flip Vertical', keys: '⇧\nV' },
    { label: 'Use as Mask', keys: '⌃\n⌘\nM' },
    { label: 'Edit Shape or Image', keys: '↩ Enter' },
    { label: 'Place Image', keys: '⇧\n⌘\nK' },
    { label: 'Crop Image', keys: '⌥\ndbl-click' },
    { label: 'Set Opacity to 10%', keys: '1' },
    { label: 'Set Opacity to 50%', keys: '5' },
    { label: 'Set Opacity to 100%', keys: '0' },
    { label: 'Copy', keys: '⌘\nC' },
    { label: 'Cut', keys: '⌘\nX' },
    { label: 'Paste', keys: '⌘\nV' },
    { label: 'Paste Over Selection', keys: '⇧\n⌘\nV' },
    { label: 'Duplicate', keys: '⌘\nD' },
    { label: 'Rename Selection', keys: '⌘\nR' },
    { label: 'Export', keys: '⇧\n⌘\nE' },
    { label: 'Copy Properties', keys: '⌥\n⌘\nC' },
    { label: 'Paste Properties', keys: '⌥\n⌘\nV' },
    { label: 'Measure to Selection', keys: '⌥' },
    { label: 'Duplicate Selection', keys: '⌥' },
    { label: 'Deep Select', keys: '⌘\nclick' },
    { label: 'Select Layer Menu', keys: '⌘\nright-click' },
    { label: 'Deep Select Within Rectangle', keys: '⌘\ndrag' },
    { label: 'Resize from Center', keys: '⌥' },
    { label: 'Resize Proportionally', keys: '⇧' },
    { label: 'Move While Resizing', keys: 'Space' },
    { label: 'Ignore Constraints (Frames Only)', keys: '⌘' },
    { label: 'Select All', keys: '⌘\nA' },
    { label: 'Select Inverse', keys: '⇧\n⌘\nA' },
    { label: 'Select None', keys: '⎋ Esc' },
    { label: 'Deep Select', keys: '⌘\nclick' },
    { label: 'Select Layer Menu', keys: '⌘\nright-click' },
    { label: 'Select Child', keys: '↩ Enter' },
    { label: 'Select Parents', keys: '⇧\n↩ Enter' },
    { label: 'Select Next Sibling', keys: '⇥ Tab' },
    { label: 'Select Previous Sibling', keys: '⇧\n⇥ Tab' },
    { label: 'Group Selection', keys: '⌘\nG' },
    { label: 'Ungroup Selection', keys: '⇧\n⌘\nG' },
    { label: 'Frame Selection', keys: '⌥\n⌘\nG' },
    { label: 'Show/Hide Selection', keys: '⇧\n⌘\nH' },
    { label: 'Lock/Unlock Selection', keys: '⇧\n⌘\nL' },
    { label: 'Pen', keys: 'P' },
    { label: 'Pencil', keys: '⇧\nP' },
    { label: 'Paint Bucket', keys: 'B' },
    { label: 'Bend Tool', keys: '⌘' },
    { label: 'Remove Fill', keys: '⌥\n/' },
    { label: 'Remove Stroke', keys: '/' },
    { label: 'Swap Fill and Stroke', keys: '⇧\nX' },
    { label: 'Outline Stroke', keys: '⇧\n⌘\nO' },
    { label: 'Flatten Selection', keys: '⌘\nE' },
    { label: 'Join Selection', keys: '⌘\nJ' },
    { label: 'Smooth Join Selection', keys: '⇧\n⌘\nJ' },
    { label: 'Delete and Heal Selection', keys: '⇧\n⌫' },
    { label: 'Bold', keys: '⌘\nB' },
    { label: 'Italic', keys: '⌘\nI' },
    { label: 'Underline', keys: '⌘\nU' },
    { label: 'Create Link', keys: '⌘\nK' },
    { label: 'Text Align Left', keys: '⌥\n⌘\nL' },
    { label: 'Text Align Center', keys: '⌥\n⌘\nT' },
    { label: 'Text Align Right', keys: '⌥\n⌘\nR' },
    { label: 'Text Align Justified', keys: '⌥\n⌘\nJ' },
    { label: 'Adjust Font Size', keys: '⇧\n⌘\n<\nand\n>' },
    { label: 'Adjust Font Weight', keys: '⌥\n⌘\n<\nand\n>' },
    { label: 'Adjust Letter Spacing', keys: '⌥\n<\nand\n>' },
    { label: 'Adjust Line Height', keys: '⇧\n⌥\n<\nand\n>' },
    { label: 'Pan', keys: 'Space\ndrag' },
    { label: 'Zoom In', keys: '+' },
    { label: 'Zoom Out', keys: '–' },
    { label: 'Zoom to 100%', keys: '⇧\n0' },
    { label: 'Zoom to Fit', keys: '⇧\n1' },
    { label: 'Zoom to Selection', keys: '⇧\n2' },
    { label: 'Zoom to Previous Frame', keys: '⇧\nN' },
    { label: 'Zoom to Next Frame', keys: 'N' },
    { label: 'Previous Page', keys: 'Page Up' },
    { label: 'Next Page', keys: 'Page Down' },
    { label: 'Find Previous Frame', keys: 'Home' },
    { label: 'Find Next Frame', keys: 'End' },
    { label: 'Show/Hide UI', keys: '⌘\n\\' },
    { label: 'Multiplayer Cursors', keys: '⌥\n⌘\n\\' },
    { label: 'Rulers', keys: '⇧\nR' },
    { label: 'Outlines', keys: '⌘\nY' },
    { label: 'Pixel Preview', keys: '⌃\nP' },
    { label: 'Layout Grids', keys: '⌃\nG' },
    { label: 'Pixel Grid', keys: '⌘\n′' },
    { label: 'Open Layers Panel', keys: '⌥\n1' },
    { label: 'Open Assets Panel', keys: '⌥\n2' },
    { label: 'Open Design Panel', keys: '⌥\n8' },
    { label: 'Open Prototype Panel', keys: '⌥\n9' },
    { label: 'Open Code Panel', keys: '⌥\n0' },
    { label: 'Move Tool', keys: 'V' },
    { label: 'Frame Tool', keys: 'F' },
    { label: 'Pen Tool', keys: 'P' },
    { label: 'Pencil Tool', keys: '⇧\nP' },
    { label: 'Text Tool', keys: 'T' },
    { label: 'Rectangle Tool', keys: 'R' },
    { label: 'Ellipse Tool', keys: 'O' },
    { label: 'Line Tool', keys: 'L' },
    { label: 'Arrow Tool', keys: '⇧\nL' },
    { label: 'Add/Show Comments', keys: 'C' },
    { label: 'Pick Color', keys: '⌃\nC' },
    { label: 'Slice Tool', keys: 'S' },
  ],
};

export default config;
